# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-13 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketshop', '0002_auto_20160513_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextra',
            name='sex',
            field=models.CharField(choices=[('M', 'Man'), ('F', 'Vrouw')], default='N', max_length=1),
        ),
    ]
