# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-13 14:29
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ticketshop', '0003_userextra_sex'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventOrganiser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_rights', models.IntegerField(choices=[(0, 'Geen rechten'), (1, 'Halve rechten'), (2, 'Alle rechten')], default=0, max_length=1)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketshop.Event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SoldTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_gen_id', models.IntegerField(max_length=30)),
                ('sold_date', models.DateTimeField(verbose_name='date sold')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('birth_date', models.DateField(blank=True, default=datetime.datetime.now, verbose_name='birth date')),
                ('sex', models.CharField(choices=[('M', 'Man'), ('F', 'Vrouw')], default='N', max_length=1)),
                ('adress', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_gen_id', models.IntegerField(max_length=30)),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('price', models.IntegerField(max_length=10)),
                ('quantity', models.IntegerField(max_length=10)),
                ('start_date', models.DateTimeField(verbose_name='date started')),
                ('end_date', models.DateTimeField(verbose_name='date ended')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketshop.Event')),
            ],
        ),
        migrations.CreateModel(
            name='UserExtraSeller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kvk_number', models.CharField(default='', max_length=30)),
                ('rekening_number', models.CharField(default='', max_length=30)),
                ('factuur_adress', models.CharField(default='', max_length=200)),
                ('user', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='soldticket',
            name='ticket_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketshop.Ticket'),
        ),
        migrations.AddField(
            model_name='soldticket',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
