# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-13 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketshop', '0004_auto_20160513_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventorganiser',
            name='admin_rights',
            field=models.IntegerField(choices=[(0, 'Geen rechten'), (1, 'Halve rechten'), (2, 'Alle rechten')], default=0),
        ),
        migrations.AlterField(
            model_name='soldticket',
            name='ticket_gen_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_gen_id',
            field=models.IntegerField(),
        ),
    ]
