# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-19 12:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketshop', '0006_soldticket_checked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='ticket_gen_id',
        ),
    ]
