# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-05 21:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketshop', '0007_remove_ticket_ticket_gen_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_url',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='ticket',
            name='max_sold',
            field=models.IntegerField(default='10'),
        ),
    ]
