# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-26 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketshop', '0010_dictionary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date ended'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date started'),
        ),
        migrations.AlterField(
            model_name='soldticket',
            name='sold_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date sold'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='end_date',
            field=models.DateTimeField(blank=True, verbose_name='date ended'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='start_date',
            field=models.DateTimeField(blank=True, verbose_name='date started'),
        ),
        migrations.AlterField(
            model_name='userextra',
            name='birth_date',
            field=models.DateField(auto_now_add=True, verbose_name='birth date'),
        ),
    ]
