# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-29 20:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketshop', '0012_auto_20160729_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketshopcustom',
            name='bg_img',
            field=models.ImageField(default='images/event/bg.jpg', upload_to='images/event/'),
        ),
        migrations.AlterField(
            model_name='ticketshopcustom',
            name='header_img',
            field=models.ImageField(default='images/event/header.jpg', upload_to='images/event/'),
        ),
    ]
