# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-30 19:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticketshop', '0015_event_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='soldticket',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ticketshop.Event'),
        ),
    ]
