# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-31 23:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketshop', '0016_soldticket_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextraseller',
            name='rekening_houder',
            field=models.CharField(default='', max_length=200),
        ),
    ]
