# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-31 23:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticketshop', '0018_userextraseller_btw_nr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userextraseller',
            name='user',
        ),
        migrations.AddField(
            model_name='userextraseller',
            name='event_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ticketshop.Event'),
        ),
    ]
