# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-06 02:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketshop', '0019_auto_20160801_0120'),
    ]

    operations = [
        migrations.CreateModel(
            name='accessRequests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sold_date', models.DateTimeField(auto_now_add=True, verbose_name='date sold')),
                ('email', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.CharField(max_length=5000),
        ),
    ]
