# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-08 21:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketshop', '0020_auto_20160806_0410'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='mollie_id',
            field=models.CharField(default='', max_length=100),
        ),
    ]
