# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-14 22:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketshop', '0022_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soldticket',
            name='ticket_gen_id',
            field=models.BigIntegerField(),
        ),
    ]
