# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-17 13:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticketshop', '0023_auto_20160815_0048'),
    ]

    operations = [
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(max_length=10)),
                ('language_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='dictionary',
            name='language_code',
        ),
        migrations.AddField(
            model_name='dictionary',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ticketshop.Languages'),
        ),
    ]
