# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-17 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketshop', '0024_auto_20161117_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictionary',
            name='language',
            field=models.CharField(default=3, max_length=10),
            preserve_default=False,
        ),
    ]
