# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-17 13:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketshop', '0029_auto_20161117_1441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dictionary',
            name='language',
        ),
        migrations.DeleteModel(
            name='Dictionary',
        ),
    ]
