# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-17 13:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticketshop', '0030_auto_20161117_1443'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=1000)),
                ('language', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ticketshop.Languages')),
            ],
        ),
    ]
