# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-25 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketshop', '0031_dictionary'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='mail_send',
            field=models.BooleanField(default=False),
        ),
    ]
