# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-03-12 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketshop', '0032_order_mail_send'),
    ]

    operations = [
        migrations.AddField(
            model_name='soldticket',
            name='email_allowed',
            field=models.BooleanField(default=False),
        ),
    ]
