# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-15 21:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketshop', '0033_soldticket_email_allowed'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='email_allowed',
            field=models.BooleanField(default=False),
        ),
    ]
