# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-24 21:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketshop', '0034_order_email_allowed'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ordered_in_language',
            field=models.CharField(default=b'unknown', max_length=10),
        ),
    ]
