# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-05-24 21:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketshop', '0039_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='soldticket',
            name='email',
            field=models.CharField(default=b'', max_length=200),
        ),
        migrations.AddField(
            model_name='soldticket',
            name='is_subticket',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ticket',
            name='person_amount',
            field=models.IntegerField(default=b'1'),
        ),
    ]
