# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-06-03 10:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticketshop', '0040_auto_20170524_2359'),
    ]

    operations = [
        migrations.AddField(
            model_name='soldticket',
            name='primary_ticket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ticketshop.SoldTicket'),
        ),
    ]
