# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-06-07 18:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketshop', '0041_soldticket_primary_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soldticket',
            name='birth_date',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name=b'birth date'),
        ),
    ]
