# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-07-16 19:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticketshop', '0042_auto_20170607_2041'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_name', models.CharField(max_length=200)),
                ('enabled', models.BooleanField(default=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketshop.Event')),
            ],
        ),
    ]
