# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-12-07 20:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketshop', '0047_eventpayments'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='marked',
            field=models.BooleanField(default=False),
        ),
    ]
