# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2018-02-28 12:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticketshop', '0048_event_marked'),
    ]

    operations = [
        migrations.CreateModel(
            name='Iframe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255)),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketshop.Event')),
            ],
        ),
    ]
