# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2018-04-03 19:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketshop', '0049_iframe'),
    ]

    operations = [
        migrations.AddField(
            model_name='guesttickets',
            name='delayed_send',
            field=models.BooleanField(default=False),
        ),
    ]
