# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2018-04-04 19:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketshop', '0050_guesttickets_delayed_send'),
    ]

    operations = [
        migrations.AddField(
            model_name='guesttickets',
            name='type',
            field=models.CharField(blank=True, default=b'', max_length=50, null=True),
        ),
    ]
