# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2018-05-09 20:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketshop', '0051_guesttickets_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextra',
            name='is_organizer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userextra',
            name='is_visitor',
            field=models.BooleanField(default=True),
        ),
    ]
