# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2018-06-04 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketshop', '0052_auto_20180509_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextra',
            name='activate_token',
            field=models.CharField(default='', max_length=255),
        ),
    ]
