# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2018-07-20 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketshop', '0053_userextra_activate_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(default='', max_length=200),
        ),
    ]
