# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2018-11-12 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketshop', '0056_order_ga_tracked'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='removed',
            field=models.BooleanField(default=False),
        ),
    ]
