# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2018-12-11 12:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticketshop', '0060_auto_20181204_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynamicurl',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ticketshop.Event'),
        ),
        migrations.AlterField(
            model_name='dynamicurl',
            name='multiticketshop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ticketshop.Multiticketshop'),
        ),
    ]
