# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2019-01-18 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketshop', '0063_order_sale_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleschannel',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
