# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2019-02-05 14:24
from __future__ import unicode_literals

import dashboard.common.validators.ImageValidator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketshop', '0064_saleschannel_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketshopcustom',
            name='bg_img',
            field=models.ImageField(default='images/event/bg.jpg', upload_to='images/event/', validators=[dashboard.common.validators.ImageValidator.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='ticketshopcustom',
            name='header_img',
            field=models.ImageField(default='images/event/header.jpg', upload_to='images/event/', validators=[dashboard.common.validators.ImageValidator.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
        ),
    ]
