# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2020-02-07 15:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketshop', '0065_auto_20190205_1524'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orderlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('mollie_id', models.TextField(blank=True)),
                ('order_id', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
