# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-08-19 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketshop', '0069_auto_20200808_0900'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='show_covid19_info',
            field=models.BooleanField(default=False),
        ),
    ]
