# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-08-22 11:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketshop', '0070_event_show_covid19_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='agreed_covid19_info',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
