# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-05-30 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketshop', '0075_auto_20220503_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='service_cost_discount_cents',
            field=models.IntegerField(default=0),
        ),
    ]
