# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-07-02 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketshop', '0076_event_service_cost_discount_cents'),
    ]

    operations = [
        migrations.AddField(
            model_name='multiticketshop',
            name='use_in_iframe',
            field=models.BooleanField(default=False),
        ),
    ]
