# Generated by Django 3.2.3 on 2022-07-28 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketshop', '0079_pageviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageviews',
            name='event_id',
            field=models.CharField(default='', max_length=200),
        ),
    ]
