# Generated by Django 3.2.3 on 2022-08-07 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticketshop', '0080_alter_pageviews_event_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpayments',
            name='approved',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='eventpayments',
            name='event',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='ticketshop.event'),
        ),
    ]
