# Generated by Django 3.2.3 on 2022-08-11 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticketshop', '0083_eventpayments_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soldticket',
            name='guest_ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ticketshop.guesttickets'),
        ),
    ]
