# Generated by Django 3.2.3 on 2022-09-26 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketshop', '0084_alter_soldticket_guest_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextraseller',
            name='house_number_addition',
            field=models.CharField(default='', max_length=6),
        ),
    ]
