# Generated by Django 3.2.3 on 2023-01-28 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketshop', '0085_userextraseller_house_number_addition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventorganiser',
            name='admin_rights',
            field=models.IntegerField(choices=[(1, 'Beheerder'), (0, 'View'), (2, 'Owner')], default=0),
        ),
    ]
