# Generated by Django 3.2.3 on 2023-01-30 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticketshop', '0086_auto_20230130_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soldticket',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ticketshop.event'),
        ),
        migrations.AlterField(
            model_name='soldticket',
            name='order_nr',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ticketshop.order'),
        ),
    ]
