# Generated by Django 3.2.3 on 2023-01-31 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketshop', '0087_auto_20230131_0017'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreReg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=200)),
                ('last_name', models.CharField(default='', max_length=200)),
                ('email', models.CharField(default='', max_length=200)),
                ('phone_number', models.CharField(default='', max_length=200)),
                ('country', models.CharField(default='', max_length=200)),
                ('notify_me', models.BooleanField()),
            ],
        ),
    ]
