# Generated by Django 3.2.3 on 2023-03-01 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketshop', '0089_alter_soldticket_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soldticket',
            name='sex',
            field=models.CharField(choices=[('M', 'Man'), ('F', 'Vrouw'), ('X', 'X'), ('U', 'Unknown')], default='N', max_length=1),
        ),
    ]
