# Generated by Django 3.2.3 on 2023-06-14 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketshop', '0090_alter_soldticket_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpayments',
            name='type',
            field=models.CharField(choices=[('', ''), ('PARTIAL-PAYMENT', 'Partial payment'), ('FINAL-PAYMENT', 'Final payment'), ('REFUNDS', 'Refunds'), ('CHARGE', 'Charge')], default='', max_length=50),
        ),
    ]
