# Generated by Django 3.2.3 on 2023-06-15 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketshop', '0092_auto_20230615_0904'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='total_person_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='event',
            name='total_service_costs',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='event',
            name='total_service_costs_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='event',
            name='total_service_costs_gross',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='event',
            name='total_tickets',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='person_amount',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='order',
            name='sold_tickets',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='total_person_amount',
            field=models.IntegerField(default='0'),
        ),
    ]
