# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2021-08-29 13:20
from __future__ import unicode_literals

import dashboard.common.validators.ImageValidator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketshop', '0072_userextraseller_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextra',
            name='avatar',
            field=models.ImageField(default='ticketshop/images/default_avatar.png', upload_to='images/user/', validators=[dashboard.common.validators.ImageValidator.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
        ),
    ]
