# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2021-09-12 11:41
from __future__ import unicode_literals

import dashboard.common.validators.ImageValidator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketshop', '0073_userextra_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextraseller',
            name='big',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='userextraseller',
            name='company_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='userextraseller',
            name='house_number',
            field=models.CharField(default='', max_length=6),
        ),
        migrations.AddField(
            model_name='userextraseller',
            name='postal_code',
            field=models.CharField(default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='userextra',
            name='avatar',
            field=models.ImageField(default='images/user/default_avatar.png', upload_to='images/user/', validators=[dashboard.common.validators.ImageValidator.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
        ),
    ]
