# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2021-09-13 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketshop', '0074_auto_20210912_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventorganiser',
            name='admin_rights',
            field=models.IntegerField(choices=[('ADMINISTRATOR', 'Beheerder'), ('OWNER', 'Inzien'), ('OWNER', 'Eigenaar')], default=0),
        ),
    ]
