# Generated by Django 3.2.3 on 2021-11-04 13:34

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ticketshop', '0075_auto_20210913_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynamicurl',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ticketshop.event'),
        ),
        migrations.AlterField(
            model_name='dynamicurl',
            name='multiticketshop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ticketshop.multiticketshop'),
        ),
        migrations.AlterField(
            model_name='eventorganiser',
            name='admin_rights',
            field=models.IntegerField(choices=[(1, 'Beheerder'), (0, 'Inzien'), (2, 'Eigenaar')], default=0),
        ),
        migrations.AlterField(
            model_name='eventorganiser',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ticketshop.event'),
        ),
        migrations.AlterField(
            model_name='eventpayments',
            name='description',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='eventpayments',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ticketshop.event'),
        ),
        migrations.AlterField(
            model_name='eventpayments',
            name='payout_date',
            field=models.DateTimeField(blank=True, verbose_name='date sold'),
        ),
        migrations.AlterField(
            model_name='guesttickets',
            name='type',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='multiticketshopevents',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ticketshop.event'),
        ),
        migrations.AlterField(
            model_name='order',
            name='ordered_in_language',
            field=models.CharField(default='unknown', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='sale_channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ticketshop.saleschannel'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='saleschannel',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ticketshop.event'),
        ),
        migrations.AlterField(
            model_name='soldticket',
            name='birth_date',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='birth date'),
        ),
        migrations.AlterField(
            model_name='soldticket',
            name='email',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='soldticket',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ticketshop.event'),
        ),
        migrations.AlterField(
            model_name='soldticket',
            name='guest_ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ticketshop.guesttickets'),
        ),
        migrations.AlterField(
            model_name='soldticket',
            name='order_nr',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ticketshop.order'),
        ),
        migrations.AlterField(
            model_name='soldticket',
            name='primary_ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ticketshop.soldticket'),
        ),
        migrations.AlterField(
            model_name='soldticket',
            name='ticket_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ticketshop.ticket'),
        ),
        migrations.AlterField(
            model_name='soldticket',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='person_amount',
            field=models.IntegerField(default='1'),
        ),
        migrations.AlterField(
            model_name='userextraseller',
            name='event_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ticketshop.event'),
        ),
    ]
