# Generated by Django 3.2.3 on 2021-12-13 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketshop', '0076_auto_20211104_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='online_event',
            field=models.BooleanField(default=False),
        ),
    ]
