# Generated by Django 3.2.3 on 2022-05-17 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketshop', '0077_event_online_event'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='online_event',
            new_name='online',
        ),
    ]
